spring:
  freemarker:
    request-context-attribute: request  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    expose-request-attributes: true

qrcUrl: https://inter-jenkins.wanmen.org/apk-down

ftp:
  username: jenkins
  password: wm2012dx
  host: 10.8.8.6
  port: 21
